server:
  port: 2333
  address: 0.0.0.0
  password: ${LAVALINK_PASSWORD}
  sources:
    youtube: false  # Disable deprecated built-in YouTube extractor
    bandcamp: true
    soundcloud: true
    twitch: true
    vimeo: true
    nico: true
    http: false     # Disable unless you need to play arbitrary HTTP URLs
    local: false    # Disable unless you want local file playback

lavalink:
  plugins:
    - dependency: "dev.lavalink.youtube:youtube-plugin:1.13.3"
      snapshot: false
    - dependency: "com.github.topi314.lavasrc:lavasrc-plugin:4.7.0"
      repository: "https://maven.lavalink.dev/releases"
      snapshot: false
  server:
    password: ${LAVALINK_PASSWORD}
    # HTTP timeout configurations to reduce timeouts
    httpConfig:
      proxyHost: ""
      proxyPort: 0
      proxyUser: ""
      proxyPassword: ""
      httpRequestTimeout: 15000  # 15 seconds
      httpConnectTimeout: 10000  # 10 seconds
    sources:
      youtube: false
      bandcamp: true
      soundcloud: true
      twitch: true
      vimeo: true
      nico: true
      http: false
      local: false
    filters:
      volume: true
      equalizer: true
      karaoke: true
      timescale: true
      tremolo: true
      vibrato: true
      distortion: true
      rotation: true
      channelMix: true
      lowPass: true
    nonAllocatingFrameBuffer: false
    bufferDurationMs: 400
    frameBufferDurationMs: 5000
    opusEncodingQuality: 10
    resamplingQuality: LOW
    trackStuckThresholdMs: 10000
    useSeekGhosting: true
    # Reduce timeout issues
    youtubePlaylistLoadLimit: 15  # Reduced from 25
    youtubeSearchEnabled: true
    playerUpdateInterval: 5
    soundcloudSearchEnabled: true
    gc-warnings: false  # Reduce log spam

plugins:
  lavasrc:
    sources:
      spotify: true # Enable Spotify source
      youtube: true
    spotify:
      # clientId & clientSecret are required for using spsearch
      clientId: "${SPOTIFY_CLIENT_ID}" # Your Spotify client ID
      clientSecret: "${SPOTIFY_CLIENT_SECRET}" # Your Spotify client secret
      # spDc: "your sp dc cookie" # the sp dc cookie used for accessing the spotify lyrics api
      countryCode: "US" # the country code you want to use for filtering the artists top tracks. See https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2
      playlistLoadLimit: 6 # The number of pages at 100 tracks each
      albumLoadLimit: 6 # The number of pages at 50 tracks each
      resolveArtistsInSearch: true # Whether to resolve artists in track search results (can be slow)
      localFiles: false # Enable local files support with Spotify playlists. Please note `uri` & `isrc` will be `null` & `identifier` will be `"local"`
      preferAnonymousToken: true # Whether to use the anonymous token for resolving tracks, artists and albums. Playlists are always resolved with the anonymous token to support autogenerated playlists.
  youtube:
    enabled: true
    allowSearch: true
    allowDirectVideoIds: true
    allowDirectPlaylistIds: true
    oauth:
      enabled: true
      refreshToken: ${YOUTUBE_REFRESH_TOKEN}
    clients:
      - TV
      - TVHTML5EMBEDDED
      - WEB
      - MWEB
      - WEBEMBEDDED
      - MUSIC
      - ANDROID_VR
      - ANDROID_MUSIC
      - IOS
    clientOptions:
      TV:
        playback: true
        playlistLoading: false
        searching: false
        videoLoading: false
      TVHTML5EMBEDDED:
        playback: true
        playlistLoading: false
        searching: true
        videoLoading: true
      WEB:
        playback: true
        playlistLoading: true
        searching: true
        videoLoading: true
      MWEB:
        playback: true
        playlistLoading: true
        searching: true
        videoLoading: true
      WEBEMBEDDED:
        playback: true
        playlistLoading: false
        searching: false
        videoLoading: true
      MUSIC:
        playback: false
        playlistLoading: false
        searching: true
        videoLoading: false
      ANDROID_VR:
        playback: true
        playlistLoading: true
        searching: true
        videoLoading: true
      ANDROID_MUSIC:
        playback: true
        playlistLoading: false
        searching: true
        videoLoading: true
      IOS:
        playback: true
        playlistLoading: true
        searching: true
        videoLoading: true

logging:
  file:
    max-history: 7
    max-size: 10MB
  level:
    root: ${LOG_LEVEL}
    lavalink: ${LOG_LEVEL}
    lavalink.server.io.SocketContext: ${LOG_LEVEL}
    com.sedmelluq.discord.lavaplayer.tools.ExceptionTools: ${LOG_LEVEL}
    dev.lavalink.youtube: ${LOG_LEVEL}
  request:
    enabled: true
    includeClientInfo: true
    includeHeaders: false
    includeQueryString: true
    includePayload: true

spring:
  main:
    banner-mode: "off"
  output:
    ansi:
      enabled: ALWAYS
